/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuhe_jnidemo_DataProvider */

#ifndef _Included_com_liuhe_jnidemo_DataProvider
#define _Included_com_liuhe_jnidemo_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuhe_jnidemo_DataProvider
 * Method:    login
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_liuhe_jnidemo_DataProvider_login
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
