package com.example.grendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.grendaodemo.bean.DaoUser2;
import com.example.grendaodemo.bean.DaoUser;

import com.example.grendaodemo.dao.DaoUser2Dao;
import com.example.grendaodemo.dao.DaoUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoUser2DaoConfig;
    private final DaoConfig daoUserDaoConfig;

    private final DaoUser2Dao daoUser2Dao;
    private final DaoUserDao daoUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoUser2DaoConfig = daoConfigMap.get(DaoUser2Dao.class).clone();
        daoUser2DaoConfig.initIdentityScope(type);

        daoUserDaoConfig = daoConfigMap.get(DaoUserDao.class).clone();
        daoUserDaoConfig.initIdentityScope(type);

        daoUser2Dao = new DaoUser2Dao(daoUser2DaoConfig, this);
        daoUserDao = new DaoUserDao(daoUserDaoConfig, this);

        registerDao(DaoUser2.class, daoUser2Dao);
        registerDao(DaoUser.class, daoUserDao);
    }
    
    public void clear() {
        daoUser2DaoConfig.clearIdentityScope();
        daoUserDaoConfig.clearIdentityScope();
    }

    public DaoUser2Dao getDaoUser2Dao() {
        return daoUser2Dao;
    }

    public DaoUserDao getDaoUserDao() {
        return daoUserDao;
    }

}
